### ISSUE TITLE
Symmetry groups pg and pgg are broken

### ISSUE THREAD

**Issue by keenanpepper** [levskaya/eschersketch#5]
If you play with https://eschersket.ch/ it's easy to determine that although pg is drawing glide reflections, they are not the correct ones and the translation that results from applying the glide reflection twice is not there, so it is not symmetry group pg.

Similarly if you play with pgg you can determine that there is a mirror plane. This symmetry group should have no mirror planes... the result is actually equivalent to pmg, not pgg.

**Comment by levskaya** [comment]
Hey - thanks so much for noticing this!  I set up these symmetry generators many years ago and just totally spaced on these bugs!
